services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - symfony_code:/var/www/symfony
      - ./symfony_project:/var/www/symfony
    depends_on:
      - database

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - symfony_code:/var/www/symfony
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_ARBITRARY: 1
    depends_on:
      - database

  mailpit:
      image: axllent/mailpit
      ports:
        - "1025:1025"
        - "8025:8025"
      environment:
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
  
volumes:
  symfony_code:
  db_data:
